image: alpine:latest

pages:
  stage: build
  script:
    - apk add nodejs npm python3 py3-pip pandoc-cli
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install --no-cache-dir -r dependencies.txt
    - npm ci
    - pandoc --resource-path static/citations/ --csl=nature.csl --citeproc --wrap=none -f markdown -t html static/citations/template.md -o dist/citations.html
    - npm run build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
